### ISSUE TITLE
Generate docs for ibm_zos_core branch v1.4.1-docs

### ISSUE THREAD

**Issue by fernandofloresg** [IBM/z_ansible_collections_doc#33]
##### SUMMARY

As part of ibm_zos_core collection 1.4.1 release, the docs have been updated and we want to keep the release notes for 1.5.0-beta.1. I created the branch **v1.4.1-docs**. Kindly generate and update the docs for RHACC ibm_zos_core.

##### ISSUE TYPE

- Update Collection

##### UPDATE REGISTRY.YML

```

################################################################################
# Copyright (c) IBM Corporation 2020, 2021
################################################################################

################################################################################
# Configuration for Red Hat certified collections as part of the
# IBM Red Hat Certified Collection on Z offering
#
# For documentation to be generated and included in the offering pending the
# certfied registry process you must also include the required fields below.
#
# Instructions:
#  <item>: The collection repository name as a dictionary element such as
#          'ibm_zos_core', 'ibm_zos_ims', etc
#  git:    The collection repository git url such as 'bm_zos_core.git'
#  stable: The Git tag or branch name to generate stable documenation.
#  latest: The Git tag or branch name to generate latest documenation.
#
# Notes:
#   Only one version of documetation is currently generated and supported.
#   Documentation is only generator for the latest branch or tag, there is plans
#   to support both latest and stable in the near future.
################################################################################
collections:
  ibm_zos_core:
    git: git@github.com:ansible-collections/ibm_zos_core.git
    stable:
    latest: v1.4.1-docs
    origin: main
  ibm_zos_ims:
    git: git@github.com:ansible-collections/ibm_zos_ims.git
    stable:
    latest: main
    origin: main
  ibm_zos_cics:
    git: git@github.com:ansible-collections/ibm_zos_cics.git
    stable:
    latest: main
    origin: main
  zhmc-ansible-modules:
    git: git@github.com:zhmcclient/zhmc-ansible-modules.git
    stable:
    latest: 1.0.2
    origin: master
  ibm_zos_sysauto:
    git: git@github.com:ansible-collections/ibm_zos_sysauto.git
    stable:
    latest: v1.0.1
    origin: main
  ibm_zosmf:
    git: git@github.com:IBM/ibm_zosmf.git
    stable:
    latest: dev
    origin: main

```
